# Generated by Django 4.1 on 2024-11-10 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('isaprojekat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentId',
            new_name='parent_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='postId',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='FollowedId',
            new_name='Followed',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='FollowerId',
            new_name='Follower',
        ),
        migrations.RenameField(
            model_name='likecomment',
            old_name='commentId',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='likecomment',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='likepost',
            old_name='postId',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='likepost',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='userId',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
